# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.8/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.8/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/exide/cmpe126project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/exide/cmpe126project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.8/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.8/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/exide/cmpe126project/CMakeFiles /Users/exide/cmpe126project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/exide/cmpe126project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmpe126project

# Build rule for target.
cmpe126project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmpe126project
.PHONY : cmpe126project

# fast build rule for target.
cmpe126project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/build
.PHONY : cmpe126project/fast

Dependencies/glad/src/gl.o: Dependencies/glad/src/gl.c.o
.PHONY : Dependencies/glad/src/gl.o

# target to build an object file
Dependencies/glad/src/gl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/Dependencies/glad/src/gl.c.o
.PHONY : Dependencies/glad/src/gl.c.o

Dependencies/glad/src/gl.i: Dependencies/glad/src/gl.c.i
.PHONY : Dependencies/glad/src/gl.i

# target to preprocess a source file
Dependencies/glad/src/gl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/Dependencies/glad/src/gl.c.i
.PHONY : Dependencies/glad/src/gl.c.i

Dependencies/glad/src/gl.s: Dependencies/glad/src/gl.c.s
.PHONY : Dependencies/glad/src/gl.s

# target to generate assembly for a file
Dependencies/glad/src/gl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/Dependencies/glad/src/gl.c.s
.PHONY : Dependencies/glad/src/gl.c.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/WordManager.o: src/WordManager.cpp.o
.PHONY : src/WordManager.o

# target to build an object file
src/WordManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/WordManager.cpp.o
.PHONY : src/WordManager.cpp.o

src/WordManager.i: src/WordManager.cpp.i
.PHONY : src/WordManager.i

# target to preprocess a source file
src/WordManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/WordManager.cpp.i
.PHONY : src/WordManager.cpp.i

src/WordManager.s: src/WordManager.cpp.s
.PHONY : src/WordManager.s

# target to generate assembly for a file
src/WordManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/WordManager.cpp.s
.PHONY : src/WordManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render.o: src/render.cpp.o
.PHONY : src/render.o

# target to build an object file
src/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/render.cpp.o
.PHONY : src/render.cpp.o

src/render.i: src/render.cpp.i
.PHONY : src/render.i

# target to preprocess a source file
src/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/render.cpp.i
.PHONY : src/render.cpp.i

src/render.s: src/render.cpp.s
.PHONY : src/render.s

# target to generate assembly for a file
src/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/render.cpp.s
.PHONY : src/render.cpp.s

src/update.o: src/update.cpp.o
.PHONY : src/update.o

# target to build an object file
src/update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/update.cpp.o
.PHONY : src/update.cpp.o

src/update.i: src/update.cpp.i
.PHONY : src/update.i

# target to preprocess a source file
src/update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/update.cpp.i
.PHONY : src/update.cpp.i

src/update.s: src/update.cpp.s
.PHONY : src/update.s

# target to generate assembly for a file
src/update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmpe126project.dir/build.make CMakeFiles/cmpe126project.dir/src/update.cpp.s
.PHONY : src/update.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cmpe126project"
	@echo "... Dependencies/glad/src/gl.o"
	@echo "... Dependencies/glad/src/gl.i"
	@echo "... Dependencies/glad/src/gl.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/WordManager.o"
	@echo "... src/WordManager.i"
	@echo "... src/WordManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render.o"
	@echo "... src/render.i"
	@echo "... src/render.s"
	@echo "... src/update.o"
	@echo "... src/update.i"
	@echo "... src/update.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

